version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HOME}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
    ports:
      - 8123:8123
  mosquitto:
    container_name: homeassistant-mosquitto
    build: 
        context: ./mosquitto
    ports:
      - 1884:1883
